import { NextResponse } from "next/server";
import dbConnect from "@/lib/db";
import Lead from "@/models/Lead";
import nodemailer from "nodemailer";

export async function GET() {
  return NextResponse.json({ status: "ready" }, { status: 200 });
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { fullName, email, phone, service, message, recaptchaToken } = body;

    // 1. Verify reCAPTCHA (Skip in development)
    if (process.env.NODE_ENV !== "development") {
      const secretKey = process.env.NEXT_PUBLIC_SECRET_KEY; // The user used this as the secret key in previous steps
      const verifyUrl = `https://www.google.com/recaptcha/api/siteverify?secret=${secretKey}&response=${recaptchaToken}`;

      const recaptchaRes = await fetch(verifyUrl, { method: "POST" });
      const recaptchaData = await recaptchaRes.json();

      if (!recaptchaData.success) {
        return NextResponse.json(
          { error: "ReCAPTCHA verification failed." },
          { status: 400 },
        );
      }
    }

    // 2. Save to MongoDB
    await dbConnect();
    const newLead = new Lead({
      fullName,
      email,
      phone,
      service,
      message,
    });
    await newLead.save();

    // 3. Send Email Notification
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_PASS,
      },
    });

    const mailOptions = {
      from: `"Talib Ali Leads" <${process.env.GMAIL_USER}>`,
      to: process.env.MAIL_TO,
      subject: `New Lead: ${fullName} - ${service}`,
      html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; border: 1px solid #eee; padding: 20px; border-radius: 10px;">
          <h2 style="color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px;">New Project Inquiry</h2>
          <p>You have received a new message from your website contact form.</p>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Full Name:</td>
              <td style="padding: 10px; border-bottom: 1px solid #eee;">${fullName}</td>
            </tr>
            <tr>
              <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Email:</td>
              <td style="padding: 10px; border-bottom: 1px solid #eee;"><a href="mailto:${email}">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Phone:</td>
              <td style="padding: 10px; border-bottom: 1px solid #eee;">${phone}</td>
            </tr>
            <tr>
              <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Service Needed:</td>
              <td style="padding: 10px; border-bottom: 1px solid #eee;">${service}</td>
            </tr>
          </table>
          <div style="margin-top: 20px; padding: 15px; background-color: #f9fafb; border-radius: 5px;">
            <p style="font-weight: bold; margin-bottom: 10px;">Message:</p>
            <p style="white-space: pre-wrap;">${message}</p>
          </div>
          <p style="margin-top: 30px; font-size: 12px; color: #666;">Generated by Talib Ali Lead Management System</p>
        </div>
      `,
    };

    await transporter.sendMail(mailOptions);

    return NextResponse.json(
      { message: "Lead saved and notification sent successfully." },
      { status: 200 },
    );
  } catch (error: any) {
    console.error("Lead API Error:", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 },
    );
  }
}
