import type { VercelRequest, VercelResponse } from "@vercel/node";
import dbConnect from "../lib/db";
import Lead from "../models/Lead";
import nodemailer from "nodemailer";

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Add CORS headers for testing if needed
  res.setHeader("Access-Control-Allow-Credentials", "true");
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader(
    "Access-Control-Allow-Methods",
    "GET,OPTIONS,PATCH,DELETE,POST,PUT",
  );
  res.setHeader(
    "Access-Control-Allow-Headers",
    "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version",
  );

  // Handle OPTIONS request for CORS
  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method === "GET") {
    return res.status(200).json({ status: "ready" });
  }

  if (req.method === "POST") {
    console.log("--- Lead API: Request Received ---");
    console.log("Runtime Info - Node Version:", process.version);
    console.log(
      "Runtime Info - Fetch Available:",
      typeof fetch !== "undefined",
    );

    try {
      const { fullName, email, phone, service, message, recaptchaToken } =
        req.body;

      console.log("Payload:", { fullName, email, phone, service, message });

      // 1. Verify reCAPTCHA (Skip in development)
      if (process.env.NODE_ENV !== "development") {
        console.log("Verifying reCAPTCHA...");
        const secretKey = process.env.RECAPTCHA_SECRET_KEY;
        const verifyUrl = `https://www.google.com/recaptcha/api/siteverify?secret=${secretKey}&response=${recaptchaToken}`;

        const recaptchaRes = await fetch(verifyUrl, { method: "POST" });
        const recaptchaData = await recaptchaRes.json();
        console.log("reCAPTCHA response:", recaptchaData);

        if (!recaptchaData.success) {
          console.error("reCAPTCHA verification failed");
          return res
            .status(400)
            .json({ error: "ReCAPTCHA verification failed." });
        }
      } else {
        console.log("reCAPTCHA verification skipped in development");
      }

      // 2. Save to MongoDB
      console.log("Connecting to MongoDB...");
      await dbConnect();
      console.log("Connected to MongoDB. Saving lead...");

      const newLead = new Lead({
        fullName,
        email,
        phone,
        service,
        message,
      });
      await newLead.save();
      console.log("Lead saved successfully to DB");

      // 3. Send Email Notification
      console.log("Preparing email notification...");
      const transporter = nodemailer.createTransport({
        service: "gmail",
        auth: {
          user: process.env.GMAIL_USER,
          pass: process.env.GMAIL_PASS,
        },
      });

      const mailOptions = {
        from: `"Talib Ali Leads" <${process.env.GMAIL_USER}>`,
        to: process.env.MAIL_TO,
        subject: `New Lead: ${fullName} - ${service}`,
        html: `
          <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; border: 1px solid #eee; padding: 20px; border-radius: 10px;">
            <h2 style="color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px;">New Project Inquiry</h2>
            <p>You have received a new message from your website contact form.</p>
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Full Name:</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee;">${fullName}</td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Email:</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee;"><a href="mailto:${email}">${email}</a></td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Phone:</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee;">${phone}</td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Service Needed:</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee;">${service}</td>
              </tr>
            </table>
            <div style="margin-top: 20px; padding: 15px; background-color: #f9fafb; border-radius: 5px;">
              <p style="font-weight: bold; margin-bottom: 10px;">Message:</p>
              <p style="white-space: pre-wrap;">${message}</p>
            </div>
            <p style="margin-top: 30px; font-size: 12px; color: #666;">Generated by Talib Ali Lead Management System</p>
          </div>
        `,
      };

      console.log("Sending email...");
      await transporter.sendMail(mailOptions);
      console.log("Email sent successfully");

      return res
        .status(200)
        .json({ message: "Lead saved and notification sent successfully." });
    } catch (error: any) {
      console.error("!!! Lead API CRITICAL ERROR !!!");
      console.error("Error Message:", error?.message || "No message found");
      console.error("Error Stack:", error?.stack || "No stack trace found");

      // Log specific error properties manually since Errors are not enumerable
      const safeError = {
        name: error?.name,
        message: error?.message,
        code: error?.code,
        status: error?.status,
        stack: error?.stack,
      };
      console.error("Safe Error Details:", safeError);

      return res.status(500).json({
        error: error?.message || "Internal Server Error",
        debug: {
          message: error?.message || "Unknown error",
          nodeVersion: process.version,
        },
      });
    }
  }

  // Fallback for unsupported methods
  return res.status(405).json({ error: "Method not allowed" });
}
