import type { VercelRequest, VercelResponse } from "@vercel/node";
import dbConnect from "../lib/db";
import Lead from "../models/Lead";
import nodemailer from "nodemailer";

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Add CORS headers for testing if needed
  res.setHeader("Access-Control-Allow-Credentials", "true");
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader(
    "Access-Control-Allow-Methods",
    "GET,OPTIONS,PATCH,DELETE,POST,PUT",
  );
  res.setHeader(
    "Access-Control-Allow-Headers",
    "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version",
  );

  // Handle OPTIONS request for CORS
  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method === "GET") {
    return res.status(200).json({ status: "ready" });
  }

  if (req.method === "POST") {
    try {
      const { fullName, email, phone, service, message, recaptchaToken } =
        req.body;

      // 1. Verify reCAPTCHA (Skip in development)
      if (process.env.NODE_ENV !== "development") {
        const secretKey = process.env.RECAPTCHA_SECRET_KEY;
        const verifyUrl = `https://www.google.com/recaptcha/api/siteverify?secret=${secretKey}&response=${recaptchaToken}`;

        const recaptchaRes = await fetch(verifyUrl, { method: "POST" });
        const recaptchaData = await recaptchaRes.json();

        if (!recaptchaData.success) {
          return res
            .status(400)
            .json({ error: "ReCAPTCHA verification failed." });
        }
      }

      // 2. Save to MongoDB
      await dbConnect();
      const newLead = new Lead({
        fullName,
        email,
        phone,
        service,
        message,
      });
      await newLead.save();

      // 3. Send Email Notification
      const transporter = nodemailer.createTransport({
        service: "gmail",
        auth: {
          user: process.env.GMAIL_USER,
          pass: process.env.GMAIL_PASS,
        },
      });

      const mailOptions = {
        from: `"Talib Ali Leads" <${process.env.GMAIL_USER}>`,
        to: process.env.MAIL_TO,
        subject: `New Lead: ${fullName} - ${service}`,
        html: `
          <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; border: 1px solid #eee; padding: 20px; border-radius: 10px;">
            <h2 style="color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px;">New Project Inquiry</h2>
            <p>You have received a new message from your website contact form.</p>
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Full Name:</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee;">${fullName}</td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Email:</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee;"><a href="mailto:${email}">${email}</a></td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Phone:</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee;">${phone}</td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; font-weight: bold;">Service Needed:</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee;">${service}</td>
              </tr>
            </table>
            <div style="margin-top: 20px; padding: 15px; background-color: #f9fafb; border-radius: 5px;">
              <p style="font-weight: bold; margin-bottom: 10px;">Message:</p>
              <p style="white-space: pre-wrap;">${message}</p>
            </div>
            <p style="margin-top: 30px; font-size: 12px; color: #666;">Generated by Talib Ali Lead Management System</p>
          </div>
        `,
      };

      await transporter.sendMail(mailOptions);

      return res
        .status(200)
        .json({ message: "Lead saved and notification sent successfully." });
    } catch (error: any) {
      console.error("Lead API Error:", error);
      return res.status(500).json({ error: "Internal Server Error" });
    }
  }

  // Fallback for unsupported methods
  return res.status(405).json({ error: "Method not allowed" });
}
